### ISSUE TITLE
Cloudformation alarm creation failed

### ISSUE THREAD

**Issue by amirmohsen** [ryanmurakami/pizza-luvrs#26]
Hey Ryan, thanks for the lesson. I'm having issues with the cloudformation template. When I try to create a stack, the alarm creation fails for all of the alarms with the following error:
```
ValidationErrornull (Service: AmazonCloudWatch; Status Code: 400; Error Code: ValidationError; Request ID: [REQUEST_ID])
```
And as a result, the creation of the rest of the resources is cancelled.

Any ideas?

**Comment by ryanmurakami** [comment]
Hi Amir!

Hmm... I don't know that there's enough information here to troubleshoot. It looks like it was an error that was thrown when running validation on the cloudformation template itself, so it could be a typo or mis-formatted yaml? Does the stack appear in the AWS Cloudformation dashboard? If so, the events section might give you more information around what specifically failed. I would look for the first chronologically failing event and that error should be relevant. 

Let me know if you find it.

**Comment by ARWhattam** [comment]
Hi Amir,

On the course I was using my local region rather than 'us-west-2' which Ryan uses in the course and I had the same error. By replacing all instances of 'us-west-2' in the template with my local region the stack then created the alarms successfully. I'm not sure what exactly caused the "ValidationErrornull" error to occur though.

Might be a bit late for you but hopefully if anyone has the same issue they will see this!

**Comment by gruffeety** [comment]
I had a similar experience, but replacing the region didn't seem to work.

**Comment by ryanmurakami** [comment]
I'll fix that in a future update. Sorry you had to go through that!
