### ISSUE TITLE
502 Bad Gateway when fired the elastic beanstalk environment! 

### ISSUE THREAD

**Issue by andycflee168** [ryanmurakami/pizza-luvrs#47]
Following the video "Configuring an Elastic Beanstalk Environment".  Set everything as told in the video and got 502 Bad Gateway when fired the elastic beanstalk environment! 

Need help!!

**Comment by ryanmurakami** [comment]
Hi @andycflee168, 

Sorry you're having issues! There are two common root causes for this. You'd probably need to do some troubleshooting for us to figure out which it is:
- Load balancer listening port is incorrect (In the course I say to use 3000, but I think it might have changed to be 8080 or 8081)
- App did not start

My suggestion is to pull the logs for the Elastic Beanstalk environment and see if you see the log `Server running at:`. If you see that, and it has a port other than 3000, then update the port. Otherwise, the app couldn't start.

**Comment by djbrady1** [comment]
I had the same 502 Bad Gateway issue. It turns out it was the port number, it needed to be 8080 instead of 3000. Thank you, Ryan for your comment. I had not thought to look in the log file until I read your comment, and that showed the correct port number. I'm so sorry, but I'm afraid I rated the module as technically incorrect. If I could change my rating I would.

**Comment by ryanmurakami** [comment]
@djbrady1 No worries, glad that worked! I'm working on an update for the course, so it'll be fixed then.
